# Site settings
title: WISE R Club
motto: We R Together
email: xmuwiserclub@163.com
description: > # this means to ignore newlines until "baseurl:"
  WISE R Club.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  wise-r

# Build settings
markdown: kramdown
