# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: wise-r

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: WISER Club

description: WISE R Club is a study group in WISE set up by Xiaojun Sun and Xi Liu in Jun 20, 2014. 
It's a place where you can find people to learn R together. It's free and self-motivated.
author:
  name: WISER Club
  email: xmuwiserclub@163.com
  github: wise-r
  bio: We R together!

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
