# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
permalink: /:year/:month/:day/:title.html
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: wise-r

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: WISER Club

description: It's a place where you can find people to learn R together.
author:
  name: WISER Club
  email: xmuwiserclub@163.com
  github: wise-r
  bio: WISE R Club a place where you can find people to learn R together.

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html

BASE_PATH:
